Add Styling
Luchy-B/bookstore pull request #5
Opened 2023-04-14 19:07 UTC by Luchy-B

- Add Styling

2023-04-14 19:36 UTC, danmainah requested changes
Hi @Luchy-B , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️

- [ ] @Luchy-B kindly ensure there are no errors when running your app, I encountered the error below when running your app 
![image](https://user-images.githubusercontent.com/61408860/232139528-999e020a-3adc-4faf-967a-06903d21e5de.png)


- [ ] @Luchy-B great work on your design however, your navbar design differs from the design given, the color of navbar items, border, and user budget on the right and when selecting a nav item it's not highlighted(made brighter than the other item, eg in the design below books is darker than categories), kindly check the comparison below

Zeplin Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/232137548-579a1f28-e25a-4c52-9277-97258b1e5519.png) |  ![image](https://user-images.githubusercontent.com/61408860/232137613-b664f03f-a340-448b-aa08-9afdc1c2e65f.png)



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-14 19:36 UTC, danmainah commented on src/Components/Boolist/Book.js
> +      </div>
- [ ] @Luchy-B kindly ensure your design matches the design given, your font, text color, and progress bar circle color, and also  update the progress button color, also check the background color highlighted in both screenshots check the comparison below for a better understanding:




Zeplin Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/232138594-39d8d298-460e-469d-a384-c042124eb11d.png) | ![image](https://user-images.githubusercontent.com/61408860/232138664-64582124-34a2-492e-9b36-b45b5513c2b9.png)

2023-04-14 19:36 UTC, danmainah commented on src/Components/Boolist/NewBookForm.js
>      </form>
- [ ] @Luchy-B great job on your design however  the form occupies larger width than in the design also the button is small kindly increase its size and ensure it's color matches the design given,


Zeplin Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/232139221-ef93c3f4-e2e2-48a0-ad15-9e1b9fb1f1bd.png) |  ![image](https://user-images.githubusercontent.com/61408860/232139283-d91e9c17-db53-4577-ac39-702b195a6fc8.png)

2023-04-15 14:26 UTC, IngDavidTM approved these changes
Hi @Luchy-B  🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 18:43 UTC, merged